version: '3.8'

services:
  emotion-detect-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - emotion-network

  # 如果需要外部数据库，可以取消注释
  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: emotion_detect
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - emotion-network

networks:
  emotion-network:
    driver: bridge

# volumes:
#   postgres_data:

