version: '3.8'

services:
  emotion-detect-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    restart: unless-stopped
    networks:
      - emotion-network

networks:
  emotion-network:
    driver: bridge